apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  labels:
    app: dotnet-app
spec:
  type: NodePort
  selector:
    app: dotnet-app
  ports:
    - nodePort: 31022
      port: 81
      targetPort: 80